"""
agents/orchestrator_agent.py
==============================
Two jobs:
  1. get_greeting() → Arjun's welcome message (called once on app load)
  2. classify_intent() → 'faq' or 'loan_application'
"""

from openai import AzureOpenAI
from prompts.orchestrator_prompt import ORCHESTRATOR_SYSTEM_PROMPT, GREETING_PROMPT
from utils.config import (
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_VERSION,
    CHAT_DEPLOYMENT,
)

client = AzureOpenAI(
    api_key=AZURE_OPENAI_API_KEY,
    azure_endpoint=AZURE_OPENAI_ENDPOINT,
    api_version=AZURE_OPENAI_API_VERSION,
)


def get_greeting() -> str:
    """
    Called once when app loads.
    Returns Arjun's warm welcome message generated by LLM.
    Falls back to hardcoded message on error.
    """
    try:
        response = client.chat.completions.create(
            model=CHAT_DEPLOYMENT,
            messages=[
                {"role": "system", "content": GREETING_PROMPT},
                {"role": "user", "content": "start"},
            ],
            temperature=0.7,
            max_tokens=100,
        )
        return response.choices[0].message.content.strip()
    except Exception:
        return "Hi there! 👋 I'm Arjun, your dedicated relationship manager. I can help you with loan products, eligibility, documents, or start your loan application. How can I help you today?"


def classify_intent(user_message: str) -> str:
    """
    Classifies user message as 'faq' or 'loan_application'.
    Defaults to 'faq' on any error.
    """
    try:
        response = client.chat.completions.create(
            model=CHAT_DEPLOYMENT,
            messages=[
                {"role": "system", "content": ORCHESTRATOR_SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
            temperature=0,
            max_tokens=10,
        )
        intent = response.choices[0].message.content.strip().lower()
        if intent not in ("faq", "loan_application"):
            return "faq"
        return intent
    except Exception:
        return "faq"


def handle_message(message: str, session_id: str, user_context: dict, chat_history: list = None) -> dict:
    """
    Main entry point called by POST /chat.

    user_context is the decoded JWT payload — None for guests browsing
    without logging in. Guests can chat freely with the FAQ agent; the
    moment intent is classified as loan_application, we return type
    "auth_required" instead of proceeding, and the frontend pops the
    login screen.

    Drives the PROACTIVE flow:
      - First message after login → ask property question with MCQ card
      - "I own a property" → ask for property documents
      - "buy a property" → show bank inventory as cards
      - Otherwise → fall through to FAQ agent

    Returns
    -------
    {
        reply   : str,
        type    : "text" | "mcq" | "property_list",
        options : list | None,       # present when type == "mcq"
        properties: list | None,     # present when type == "property_list"
    }
    """
    from agents.property_agent import get_property_choice_message, get_bank_inventory
    from session_store import get_session

    chat_history = chat_history or []
    session = get_session(session_id)
    lower = message.lower().strip()

    # ── Guest (not logged in): detect loan intent and require login first ──
    if user_context is None:
        wants_property_flow = (
            lower in ("lap", "i own a property", "home_loan", "i want to buy a property")
            or "own a property" in lower
            or "loan against" in lower
            or "buy a property" in lower
        )
        intent = "loan_application" if wants_property_flow else classify_intent(message)

        if intent == "loan_application":
            return {
                "reply": (
                    "I'd love to help you get that started! To move forward with a loan "
                    "application I'll just need you to sign in or create an account first — "
                    "it only takes a minute."
                ),
                "type": "auth_required",
            }
        # Otherwise fall through to the FAQ agent below — guests can browse freely.

    else:
        # ── First touch after login: greet by name, ask property question ──
        if session.get("active_step") is None and session.get("full_name"):
            card = get_property_choice_message()
            return {
                "reply": f"Welcome back, {session['full_name'].split()[0]}! {card['message']}",
                "type": "mcq",
                "options": card["options"],
            }

        # ── User picked LAP ──
        if lower in ("lap", "i own a property") or "own a property" in lower or "loan against" in lower:
            return {
                "reply": (
                    "Perfect. To verify your property I'll need a few details from your "
                    "Sale Deed — the registration number, the address, and the area in sq. ft. "
                    "You can upload the document and I'll extract these, or type them in directly."
                ),
                "type": "document_request",
                "doc_type": "sale_deed",
            }

        # ── User picked Home Loan / Bank Inventory ──
        if lower in ("home_loan", "i want to buy a property") or "buy a property" in lower or "show me" in lower:
            inv = get_bank_inventory()
            return {
                "reply": f"Here are {inv['count']} properties available right now, all fast-tracked for financing:",
                "type": "property_list",
                "properties": inv["properties"],
            }

    # ── Default: FAQ agent (works for guests and authenticated users alike) ──
    from agents.faq_agent import faq_agent
    answer, scored_docs = faq_agent(message, chat_history)
    return {
        "reply": answer,
        "type": "text",
        "sources": scored_docs,
    }