"""
graph/state.py
==============
Shared LangGraph State Schema for the Banking Multi-Agent Loan & Property System.

This TypedDict defines every field that flows through the StateGraph.
All agents READ from this state and WRITE partial updates back.
LangGraph merges updates automatically via its reducer logic.

Design principles:
  - Every field is Optional with a default of None so agents can safely
    check `if state["field"]` without KeyError on first invocation.
  - Nested structures use typed dicts (not plain dicts) for IDE support.
  - Enum-style string literals are used for status/decision fields to
    keep routing logic in edges.py readable and typo-proof.
  - All monetary values are in INR (Indian Rupees) as float.
  - All scores are normalised 0–100 as float unless noted otherwise.
"""

from __future__ import annotations

from typing import Any, Literal, Optional, TypedDict


# ---------------------------------------------------------------------------
# Nested sub-schemas (used as field types inside BankingState)
# ---------------------------------------------------------------------------


class ChatMessage(TypedDict):
    """
    A single turn in the conversation between the user and the system.

    Used by:  orchestrator_agent, faq_agent, recommendation_agent
    """

    role: Literal["user", "assistant", "system"]
    # "user"      → message typed by the human
    # "assistant" → response generated by an agent or LLM
    # "system"    → internal status message shown in the UI timeline

    content: str
    # Raw text of the message. Markdown is supported for assistant turns.

    agent: Optional[str]
    # Which agent produced this message, e.g. "faq_agent", "recommendation_agent".
    # None for user messages.

    timestamp: Optional[str]
    # ISO-8601 UTC timestamp string, e.g. "2025-06-01T10:32:00Z".
    # Set by the agent at write time.


class DocumentData(TypedDict):
    """
    Extracted fields from a single uploaded document.

    Populated by:  kyc_agent (identity docs), property_agent (property docs)
    Read by:       kyc_agent, loan_eligibility_agent, recommendation_agent
    """

    doc_type: Literal[
        "aadhaar", "pan", "passport", "voter_id",
        "salary_slip", "bank_statement", "itr", "form_16",
        "sale_deed", "property_tax_receipt", "encumbrance_cert", "registry"
    ]
    # Which document category this extraction belongs to.

    raw_text: Optional[str]
    # Full OCR text extracted from the document before LLM field parsing.

    extracted_fields: dict[str, Any]
    # Key-value pairs parsed from the document.
    # Examples:
    #   Aadhaar  → {"name": "Ramesh Kumar", "dob": "1988-04-12", "uid": "XXXX-XXXX-7890"}
    #   PAN      → {"pan_number": "ABCDE1234F", "name": "Ramesh Kumar"}
    #   Salary   → {"employer": "Infosys Ltd", "gross_salary": 95000, "month": "2025-05"}
    #   Sale deed→ {"owner_name": "Ramesh Kumar", "area_sqft": 1200, "registration_date": "2019-11-20"}

    verified: bool
    # True if the mock KYC API or land registry API confirmed the document is valid.

    verification_source: Optional[str]
    # Which mock API confirmed it, e.g. "mock_kyc_api", "mock_land_registry_api".


class CustomerProfile(TypedDict):
    """
    Full profile of an authenticated customer, loaded from customers.json
    by account_discovery_agent via mock_customer_lookup().

    Read by:  kyc_agent (skip check), risk_agent, credit_agent,
              loan_eligibility_agent, recommendation_agent
    """

    customer_id: str
    name: str
    mobile: str
    email: Optional[str]
    pan: str
    aadhaar_hash: str          # Hashed; never store raw Aadhaar
    date_of_birth: str         # ISO-8601 date string "YYYY-MM-DD"
    address: str

    account_number: Optional[str]
    account_type: Optional[Literal["savings", "current", "salary"]]
    account_balance: Optional[float]   # INR

    employment_type: Optional[Literal["salaried", "self_employed", "business", "retired"]]
    employer_name: Optional[str]
    employment_months: Optional[int]   # Months at current employer

    monthly_income: Optional[float]    # INR, gross
    existing_emi_total: Optional[float] # INR, sum of all active EMIs

    transaction_summary: Optional[dict[str, Any]]
    # Aggregated from mock_transaction_analysis_api():
    # {
    #   "avg_monthly_credit": 92000,
    #   "avg_monthly_debit":  61000,
    #   "cash_flow_stability": "stable",   # "stable" | "volatile" | "declining"
    #   "months_analysed": 12
    # }

    existing_loans: Optional[list[dict[str, Any]]]
    # Each entry: {"loan_type": "home", "outstanding": 1200000, "emi": 18000, "bank": "HDFC"}


class PropertyReport(TypedDict):
    """
    Consolidated output of property_agent after calling all four
    property-related mock APIs.

    Read by:  orchestrator (routing), risk_agent, loan_eligibility_agent,
              recommendation_agent
    """

    property_id: str
    address: str
    owner_name: str

    # --- Ownership & Legal ---
    ownership_verified: bool
    legal_disputes: bool           # True = active litigation found
    mortgage_status: Literal["clear", "mortgaged", "partially_released"]
    encumbrance_clear: bool        # True = no encumbrance found
    registry_valid: bool

    # --- Valuation ---
    market_value: float            # INR, from mock_property_valuation_api
    carpet_area_sqft: float
    property_type: Literal["apartment", "independent_house", "plot", "commercial"]
    property_age_years: int

    # --- Location ---
    latitude: float
    longitude: float
    flood_zone: bool
    transit_distance_km: float     # Distance to nearest metro/railway
    area_quality_tier: Literal["premium", "good", "average", "below_average"]

    # --- Risk Indicators ---
    crime_score: float             # 0–100; higher = more crime
    area_risk_rating: Literal["low", "medium", "high"]

    # --- Bank Relationship ---
    is_tied_with_bank: bool
    # True → fast-track loan flow; skip full risk+credit pipeline

    # --- Composite Score ---
    property_score: float          # 0–100; computed by property_service.py
    property_score_breakdown: dict[str, float]
    # e.g. {"ownership": 25.0, "legal": 20.0, "valuation": 30.0, "location": 25.0}


class RiskReport(TypedDict):
    """
    Output of risk_agent. Combines fraud detection and transaction analysis.

    Read by:  loan_eligibility_agent, recommendation_agent, escalation_agent
    """

    risk_score: float              # 0–100; higher = riskier
    risk_band: Literal["low", "medium", "high", "very_high"]

    fraud_risk_score: float        # 0–100, from mock_fraud_detection_api
    identity_mismatch: bool        # Name/DOB inconsistency across documents
    watchlist_hit: bool            # Customer flagged in any watchlist

    employment_stability: Literal["stable", "moderate", "unstable"]
    cash_flow_stability: Literal["stable", "volatile", "declining"]

    debt_burden_ratio: float       # existing_emi_total / monthly_income
    # e.g. 0.35 means 35% of income already committed to EMIs

    risk_narrative: str
    # LLM-generated plain-English summary, e.g.:
    # "The applicant shows stable employment at a reputed firm for 36 months.
    #  Transaction history is consistent with declared income. Fraud risk is low."

    flags: list[str]
    # Specific flags raised, e.g. ["high_cash_withdrawal", "salary_inconsistency"]


class CreditReport(TypedDict):
    """
    Output of credit_agent. Aggregates three bureau mock scores.

    Read by:  loan_eligibility_agent, recommendation_agent, escalation_agent
    """

    cibil_score: int               # 300–900
    experian_score: int            # 300–900
    equifax_score: int             # 300–900
    aggregated_score: int          # Median of the three bureau scores

    creditworthiness_rating: Literal["excellent", "good", "fair", "poor", "very_poor"]
    # excellent → 800+, good → 700–799, fair → 600–699,
    # poor → 500–599, very_poor → <500

    delinquency_count: int         # Number of missed payments in last 24 months
    credit_utilization: float      # 0.0–1.0; fraction of revolving credit used
    oldest_account_years: float    # Age of oldest credit account

    bureau_responses: dict[str, Any]
    # Raw responses from each mock bureau for audit trail:
    # {"cibil": {...}, "experian": {...}, "equifax": {...}}


class LoanDecision(TypedDict):
    """
    Final structured output of loan_eligibility_agent.

    Read by:  recommendation_agent, escalation_agent, API response layer
    """

    decision: Literal[
        "approved",
        "partial_approval",
        "conditional_approval",
        "inspection_required",
        "rejected"
    ]

    eligible_amount: float         # INR; maximum loan amount approved
    requested_amount: Optional[float]  # INR; what the user asked for

    interest_rate: float           # Annual %, e.g. 8.75
    loan_tenure_months: int        # e.g. 240 for 20-year home loan
    monthly_emi: float             # INR; calculated EMI at approved amount

    dti_ratio: float               # Debt-to-income ratio post loan, e.g. 0.42
    ltv_ratio: float               # Loan-to-value ratio, e.g. 0.75

    repayment_probability: float   # 0.0–1.0; model confidence of full repayment

    conditions: list[str]
    # Conditions for conditional_approval or inspection_required:
    # ["Submit NOC from existing lender", "Property inspection mandatory"]

    rejection_reasons: list[str]
    # Non-empty only when decision == "rejected":
    # ["Credit score below minimum threshold", "DTI exceeds 55%"]

    policy_rules_applied: dict[str, Any]
    # Snapshot of which rules from policy_rules.json were decisive:
    # {"min_credit_score": 650, "max_dti": 0.55, "max_ltv": 0.80}


class AgentStatus(TypedDict):
    """
    Execution status of a single agent node.

    Stored in state["agent_statuses"] as a dict keyed by agent name.
    Read by:  StatusPage.tsx via GET /api/status/{session_id}
    """

    status: Literal["pending", "running", "done", "failed", "skipped"]
    started_at: Optional[str]      # ISO-8601 timestamp
    completed_at: Optional[str]
    error_message: Optional[str]   # Set if status == "failed"
    duration_seconds: Optional[float]


class EscalationReport(TypedDict):
    """
    Output of escalation_agent. Structured brief for human review.

    Read by:  recommendation_agent, API response layer
    """

    escalation_id: str             # UUID for tracking
    reason: str                    # Short reason, e.g. "Borderline credit score"
    severity: Literal["low", "medium", "high"]

    summary: str                   # LLM-generated case summary for the reviewer
    flags_raised: list[str]
    suggested_checks: list[str]    # e.g. ["Verify employment with HR", "Site visit"]

    assigned_to: Optional[str]     # Mock staff name or None if unassigned
    created_at: str


# ---------------------------------------------------------------------------
# Primary State Schema
# ---------------------------------------------------------------------------


class BankingState(TypedDict):
    """
    Master state dictionary shared across all LangGraph agent nodes.

    LangGraph passes this dict into every node function and merges
    the returned partial dict back into the global state.

    Organised into six logical sections:
      1. Session & User Classification
      2. Authentication & Customer Identity
      3. KYC & Document Handling
      4. Property Analysis
      5. Financial Assessment (Risk + Credit + Eligibility)
      6. Decision & Output
      7. Orchestration & Observability
    """

    # -----------------------------------------------------------------------
    # SECTION 1 — Session & User Classification
    # -----------------------------------------------------------------------

    session_id: str
    # Unique ID for this loan application session.
    # Generated by the API layer on first POST /api/chat.
    # Used as the LangGraph thread_id for checkpointing.
    # Set by: API layer (main.py)
    # Read by: all agents, checkpointer, status endpoint

    user_type: Optional[Literal["anonymous", "authenticated"]]
    # Determined by orchestrator_agent based on whether a valid
    # auth token was provided in the initial request.
    # "anonymous"     → routed to faq_agent only
    # "authenticated" → routed to auth_agent, then full loan pipeline
    # Set by: orchestrator_agent
    # Read by: edges.py (route_by_user_type)

    intent: Optional[Literal["faq", "loan_application", "status_check", "document_upload"]]
    # What the user wants to do, classified by orchestrator_agent
    # from the first user message.
    # Set by: orchestrator_agent
    # Read by: edges.py

    messages: list[ChatMessage]
    # Full conversation history including user messages and agent responses.
    # Accumulates across turns. The LLM agents (faq, recommendation,
    # escalation) receive this as their chat history context.
    # Set by: every agent that produces a user-visible message
    # Default: []

    # -----------------------------------------------------------------------
    # SECTION 2 — Authentication & Customer Identity
    # -----------------------------------------------------------------------

    is_authenticated: Optional[bool]
    # True after auth_agent successfully validates the session token
    # via mock_auth_api(). False if token is invalid or expired.
    # Set by: auth_agent
    # Read by: edges.py (route_after_auth)

    customer_id: Optional[str]
    # Unique customer identifier returned by mock_auth_api().
    # Used as the lookup key for all subsequent mock API calls.
    # Set by: auth_agent
    # Read by: account_discovery_agent, risk_agent, credit_agent,
    #           mock_customer_lookup, mock_transaction_analysis_api

    is_existing_customer: Optional[bool]
    # True if customer_id found in customers.json with kyc_status == "verified".
    # Existing customers skip full KYC and only provide updated documents
    # when specifically required.
    # Set by: account_discovery_agent
    # Read by: edges.py (route_after_account_discovery)

    customer_profile: Optional[CustomerProfile]
    # Full customer record loaded from customers.json.
    # None for new customers until KYC completes.
    # Set by: account_discovery_agent (existing) or kyc_agent (new)
    # Read by: risk_agent, credit_agent, loan_eligibility_agent,
    #           recommendation_agent

    # -----------------------------------------------------------------------
    # SECTION 3 — KYC & Document Handling
    # -----------------------------------------------------------------------

    kyc_status: Optional[Literal["not_started", "in_progress", "verified", "failed", "skipped"]]
    # Lifecycle status of the KYC process.
    # "skipped" is set for existing customers who already have verified KYC.
    # "failed"  triggers escalation_agent.
    # Set by: kyc_agent, account_discovery_agent (→ "skipped")
    # Read by: edges.py (route_after_kyc), loan_eligibility_agent

    uploaded_documents: Optional[list[DocumentData]]
    # All documents uploaded by the user in this session, with extracted fields.
    # Grows as the user uploads files via POST /api/documents/upload.
    # Set by: kyc_agent (identity docs), property_agent (property docs)
    # Default: []

    kyc_verification_result: Optional[dict[str, Any]]
    # Raw response from mock_kyc_api() for audit trail.
    # {"name_match": True, "dob_match": True, "address_verified": True}
    # Set by: kyc_agent

    missing_documents: Optional[list[str]]
    # Documents still required from the user.
    # e.g. ["itr", "encumbrance_cert"]
    # Set by: kyc_agent, property_agent
    # Read by: orchestrator_agent (to prompt user for uploads),
    #           recommendation_agent

    # -----------------------------------------------------------------------
    # SECTION 4 — Property Analysis
    # -----------------------------------------------------------------------

    property_id: Optional[str]
    # ID of the property being offered as collateral.
    # Provided by the user during the loan application form.
    # Set by: orchestrator_agent (extracted from user input)
    # Read by: property_agent

    property_report: Optional[PropertyReport]
    # Full consolidated output of property_agent.
    # Set by: property_agent
    # Read by: edges.py (route_by_property_status), risk_agent,
    #           loan_eligibility_agent, recommendation_agent

    property_status: Optional[Literal["tied", "untied", "verification_failed"]]
    # Simplified routing flag derived from property_report.is_tied_with_bank.
    # "tied"               → fast-track loan flow (skip risk + credit agents)
    # "untied"             → full risk + credit assessment required
    # "verification_failed"→ escalate
    # Set by: property_agent (derived from PropertyReport)
    # Read by: edges.py (route_by_property_status)

    requested_loan_amount: Optional[float]
    # INR amount the customer wants to borrow.
    # Extracted from user's message by orchestrator_agent.
    # Set by: orchestrator_agent
    # Read by: loan_eligibility_agent

    # -----------------------------------------------------------------------
    # SECTION 5 — Financial Assessment
    # -----------------------------------------------------------------------

    risk_report: Optional[RiskReport]
    # Output of risk_agent.
    # None if property is tied (fast-track skips risk assessment).
    # Set by: risk_agent
    # Read by: loan_eligibility_agent, recommendation_agent, escalation_agent

    credit_report: Optional[CreditReport]
    # Output of credit_agent.
    # None if property is tied (fast-track skips credit assessment).
    # Set by: credit_agent
    # Read by: loan_eligibility_agent, recommendation_agent, escalation_agent

    fast_track: Optional[bool]
    # True when property_status == "tied".
    # Signals loan_eligibility_agent to use relaxed underwriting rules
    # and skip risk/credit thresholds (bank already holds the asset).
    # Set by: edges.py or property_agent
    # Read by: loan_eligibility_agent, recommendation_agent

    loan_decision: Optional[LoanDecision]
    # Final structured loan output from loan_eligibility_agent.
    # Set by: loan_eligibility_agent
    # Read by: recommendation_agent, escalation_agent, API response

    # -----------------------------------------------------------------------
    # SECTION 6 — Decision & Output
    # -----------------------------------------------------------------------

    recommendation_text: Optional[str]
    # LLM-generated customer-facing recommendation letter.
    # Summarises property score, risk band, credit rating, eligibility,
    # EMI breakdown, and next steps in plain language.
    # Set by: recommendation_agent
    # Read by: API response → ChatWidget.tsx in frontend

    requires_human_review: Optional[bool]
    # True when escalation_agent is triggered.
    # Causes the API to include an escalation notice in the response.
    # Set by: escalation_agent
    # Read by: API response layer, recommendation_agent

    escalation_report: Optional[EscalationReport]
    # Structured brief for the human reviewer.
    # Set by: escalation_agent
    # Read by: API response layer (exposed to bank staff dashboard)

    # -----------------------------------------------------------------------
    # SECTION 7 — Orchestration & Observability
    # -----------------------------------------------------------------------

    agent_statuses: dict[str, AgentStatus]
    # Execution status of every agent, keyed by agent name.
    # e.g. {"auth_agent": {"status": "done", ...},
    #        "kyc_agent":  {"status": "skipped", ...}}
    # Updated by each agent at start and completion.
    # Read by: GET /api/status/{session_id} → StatusPage.tsx (AgentTimeline)
    # Default: {}

    current_agent: Optional[str]
    # Name of the agent currently executing.
    # Set by each agent at the start of its run.
    # Used by the SSE stream to push live "agent X is running" events.

    errors: list[dict[str, Any]]
    # Accumulated non-fatal errors from any agent.
    # Each entry: {"agent": "property_agent", "code": "API_TIMEOUT",
    #              "message": "mock_land_registry_api timed out after 3s",
    #              "timestamp": "2025-06-01T10:35:12Z"}
    # Fatal errors set agent_statuses[agent]["status"] = "failed"
    # and may trigger escalation_agent.
    # Default: []

    retry_counts: dict[str, int]
    # How many times each agent has retried a failed API call.
    # e.g. {"property_agent": 2}
    # Used by base_agent.py to enforce max_retries = 3.
    # Default: {}

    graph_version: str
    # Version string of the compiled graph, e.g. "1.0.0".
    # Stamped onto every session for debugging and A/B testing.
    # Set by: graph_builder.py at compile time.

    created_at: str
    # ISO-8601 UTC timestamp when this session was first initialised.
    # Set by: API layer (main.py) on session creation.

    updated_at: str
    # ISO-8601 UTC timestamp of the last state mutation.
    # Updated by every agent after writing to state.
    # Used to detect stale/abandoned sessions.


# ---------------------------------------------------------------------------
# Default state factory
# ---------------------------------------------------------------------------

def make_initial_state(session_id: str, graph_version: str = "1.0.0") -> BankingState:
    """
    Returns a BankingState with all optional fields set to None/[]/{}.

    Call this in main.py when a new session starts:

        state = make_initial_state(session_id=str(uuid4()))
        app.invoke(state, config={"configurable": {"thread_id": state["session_id"]}})
    """
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).isoformat()

    return BankingState(
        # Section 1 — Session
        session_id=session_id,
        user_type=None,
        intent=None,
        messages=[],

        # Section 2 — Auth & Identity
        is_authenticated=None,
        customer_id=None,
        is_existing_customer=None,
        customer_profile=None,

        # Section 3 — KYC & Documents
        kyc_status=None,
        uploaded_documents=[],
        kyc_verification_result=None,
        missing_documents=[],

        # Section 4 — Property
        property_id=None,
        property_report=None,
        property_status=None,
        requested_loan_amount=None,

        # Section 5 — Financial Assessment
        risk_report=None,
        credit_report=None,
        fast_track=None,
        loan_decision=None,

        # Section 6 — Output
        recommendation_text=None,
        requires_human_review=None,
        escalation_report=None,

        # Section 7 — Orchestration
        agent_statuses={},
        current_agent=None,
        errors=[],
        retry_counts={},
        graph_version=graph_version,
        created_at=now,
        updated_at=now,
    )


# ---------------------------------------------------------------------------
# Convenience type alias used in agent function signatures
# ---------------------------------------------------------------------------

# Every agent is typed as:  def my_agent(state: BankingState) -> BankingState
# LangGraph merges the returned dict into the global state automatically.
